package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateCore gera o arquivo sqlc/generated/db.go com interface DBTX e struct Queries
func GenerateCore(projectRoot string) error {
	generatedDir := filepath.Join(projectRoot, "sqlc/generated")
	dbFile := filepath.Join(generatedDir, "db.go")

	// Criar diretório generated se não existir
	if err := os.MkdirAll(generatedDir, 0755); err != nil {
		return fmt.Errorf("erro ao criar diretório generated: %v", err)
	}

	file, err := os.Create(dbFile)
	if err != nil {
		return fmt.Errorf("erro ao criar arquivo %s: %v", dbFile, err)
	}
	defer file.Close()

	// Header
	fmt.Fprintf(file, "// Code generated by scripts/generate-core.go. DO NOT EDIT.\n")
	fmt.Fprintf(file, "package generated\n\n")
	fmt.Fprintf(file, "import (\n")
	fmt.Fprintf(file, "\t\"context\"\n\n")
	fmt.Fprintf(file, "\t\"github.com/jackc/pgx/v5\"\n")
	fmt.Fprintf(file, "\t\"github.com/jackc/pgx/v5/pgconn\"\n")
	fmt.Fprintf(file, ")\n\n")

	// Interface DBTX
	fmt.Fprintf(file, "// DBTX é uma interface que abstrai conexões e transações\n")
	fmt.Fprintf(file, "type DBTX interface {\n")
	fmt.Fprintf(file, "\tExec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)\n")
	fmt.Fprintf(file, "\tQuery(context.Context, string, ...interface{}) (pgx.Rows, error)\n")
	fmt.Fprintf(file, "\tQueryRow(context.Context, string, ...interface{}) pgx.Row\n")
	fmt.Fprintf(file, "}\n\n")

	// Struct Queries
	fmt.Fprintf(file, "// Queries contém métodos para acessar o banco de dados\n")
	fmt.Fprintf(file, "type Queries struct {\n")
	fmt.Fprintf(file, "\tdb DBTX\n")
	fmt.Fprintf(file, "}\n\n")

	// New
	fmt.Fprintf(file, "// New cria uma nova instância de Queries\n")
	fmt.Fprintf(file, "func New(db DBTX) *Queries {\n")
	fmt.Fprintf(file, "\treturn &Queries{db: db}\n")
	fmt.Fprintf(file, "}\n\n")

	// WithTx
	fmt.Fprintf(file, "// WithTx cria uma nova instância de Queries com uma transação\n")
	fmt.Fprintf(file, "func (q *Queries) WithTx(tx pgx.Tx) *Queries {\n")
	fmt.Fprintf(file, "\treturn &Queries{db: tx}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Printf("✅ Gerado: %s\n", dbFile)
	return nil
}
