package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// createGeneratedFile creates a new file and writes the standard header
// Returns the file handle and any error encountered
func createGeneratedFile(filePath string, packageName string) (*os.File, error) {
	// Ensure directory exists
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create directory: %w", err)
	}

	file, err := os.Create(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to create file: %w", err)
	}

	// Write standard header
	fmt.Fprintf(file, "// Code generated by prisma generate. DO NOT EDIT.\n")
	fmt.Fprintf(file, "package %s\n\n", packageName)

	return file, nil
}
