package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// createGeneratedFile creates a new file and writes the standard header
// Returns the file handle and any error encountered
func createGeneratedFile(filePath string, packageName string) (*os.File, error) {
	// Ensure directory exists
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create directory: %w", err)
	}

	file, err := os.Create(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to create file: %w", err)
	}

	// Write standard header
	fmt.Fprintf(file, "// Code generated by prisma generate. DO NOT EDIT.\n")
	fmt.Fprintf(file, "package %s\n\n", packageName)

	return file, nil
}

// writeImports writes an import block to the file
func writeImports(file *os.File, imports []string) {
	if len(imports) == 0 {
		return
	}

	fmt.Fprintf(file, "import (\n")
	for _, imp := range imports {
		fmt.Fprintf(file, "\t%q\n", imp)
	}
	fmt.Fprintf(file, ")\n\n")
}

// writeImportsWithGroups writes an import block with stdlib and third-party separated
// Does not close the import block - caller should close it if additional imports are needed
func writeImportsWithGroups(file *os.File, stdlib []string, thirdParty []string) {
	if len(stdlib) == 0 && len(thirdParty) == 0 {
		return
	}

	fmt.Fprintf(file, "import (\n")

	// Write stdlib imports
	for _, imp := range stdlib {
		fmt.Fprintf(file, "\t%q\n", imp)
	}

	// Add blank line if both exist
	if len(stdlib) > 0 && len(thirdParty) > 0 {
		fmt.Fprintf(file, "\n")
	}

	// Write third-party imports
	for _, imp := range thirdParty {
		fmt.Fprintf(file, "\t%q\n", imp)
	}
}

// closeImports closes an import block
func closeImports(file *os.File) {
	fmt.Fprintf(file, ")\n\n")
}
