package generator

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/carlosnayan/prisma-go-client/internal/parser"
)

// GenerateHelpers gera funções helper type-safe no pacote db
func GenerateHelpers(schema *parser.Schema, outputDir string) error {
	// Detect user module
	userModule, err := detectUserModule(outputDir)
	if err != nil {
		return fmt.Errorf("failed to detect user module: %w", err)
	}

	helpersFile := filepath.Join(outputDir, "helpers.go")
	return generateHelpersFile(helpersFile, userModule, outputDir)
}

// generateHelpersFile gera o arquivo com funções helper type-safe
func generateHelpersFile(filePath string, userModule, outputDir string) error {
	file, err := os.Create(filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	// Header
	fmt.Fprintf(file, "// Code generated by prisma generate. DO NOT EDIT.\n")
	fmt.Fprintf(file, "package db\n\n")

	// Calculate import path for inputs
	_, _, inputsPath, err := calculateImportPath(userModule, outputDir)
	if err != nil {
		// Fallback
		inputsPath = "github.com/carlosnayan/prisma-go-client/db/inputs"
	}

	fmt.Fprintf(file, "import (\n")
	fmt.Fprintf(file, "\t\"time\"\n")
	fmt.Fprintf(file, "\t\"encoding/json\"\n")
	fmt.Fprintf(file, "\tinputs %q\n", inputsPath)
	fmt.Fprintf(file, ")\n\n")

	// String helpers
	generateStringHelpers(file)

	// Int helpers
	generateIntHelpers(file)

	// Int64 helpers
	generateInt64Helpers(file)

	// Float helpers
	generateFloatHelpers(file)

	// Boolean helpers
	generateBooleanHelpers(file)

	// DateTime helpers
	generateDateTimeHelpers(file)

	// Json helpers
	generateJsonHelpers(file)

	// Bytes helpers
	generateBytesHelpers(file)

	return nil
}

func generateStringHelpers(file *os.File) {
	fmt.Fprintf(file, "// String helper functions for StringFilter\n\n")
	fmt.Fprintf(file, "func Contains(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{Contains: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func StartsWith(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{StartsWith: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func EndsWith(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{EndsWith: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func ContainsInsensitive(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{ContainsInsensitive: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func StartsWithInsensitive(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{StartsWithInsensitive: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func EndsWithInsensitive(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{EndsWithInsensitive: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func String(value string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func StringIn(values ...string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{In: values}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func StringNotIn(values ...string) *inputs.StringFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.StringFilter{NotIn: values}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateIntHelpers(file *os.File) {
	fmt.Fprintf(file, "// Int helper functions for IntFilter\n\n")
	fmt.Fprintf(file, "func Int(value int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntGt(value int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{Gt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntGte(value int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{Gte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntLt(value int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{Lt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntLte(value int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{Lte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntIn(values ...int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{In: values}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func IntNotIn(values ...int) *inputs.IntFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.IntFilter{NotIn: values}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateInt64Helpers(file *os.File) {
	fmt.Fprintf(file, "// Int64 helper functions for Int64Filter\n\n")
	fmt.Fprintf(file, "func Int64(value int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64Gt(value int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{Gt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64Gte(value int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{Gte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64Lt(value int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{Lt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64Lte(value int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{Lte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64In(values ...int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{In: values}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func Int64NotIn(values ...int64) *inputs.Int64Filter {\n")
	fmt.Fprintf(file, "\treturn &inputs.Int64Filter{NotIn: values}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateFloatHelpers(file *os.File) {
	fmt.Fprintf(file, "// Float helper functions for FloatFilter\n\n")
	fmt.Fprintf(file, "func Float(value float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatGt(value float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{Gt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatGte(value float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{Gte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatLt(value float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{Lt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatLte(value float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{Lte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatIn(values ...float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{In: values}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func FloatNotIn(values ...float64) *inputs.FloatFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.FloatFilter{NotIn: values}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateBooleanHelpers(file *os.File) {
	fmt.Fprintf(file, "// Boolean helper functions for BooleanFilter\n\n")
	fmt.Fprintf(file, "func Bool(value bool) *inputs.BooleanFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.BooleanFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateDateTimeHelpers(file *os.File) {
	fmt.Fprintf(file, "// DateTime helper functions for DateTimeFilter\n\n")
	fmt.Fprintf(file, "func DateTime(value time.Time) *inputs.DateTimeFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.DateTimeFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func DateTimeGt(value time.Time) *inputs.DateTimeFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.DateTimeFilter{Gt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func DateTimeGte(value time.Time) *inputs.DateTimeFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.DateTimeFilter{Gte: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func DateTimeLt(value time.Time) *inputs.DateTimeFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.DateTimeFilter{Lt: &value}\n")
	fmt.Fprintf(file, "}\n\n")

	fmt.Fprintf(file, "func DateTimeLte(value time.Time) *inputs.DateTimeFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.DateTimeFilter{Lte: &value}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateJsonHelpers(file *os.File) {
	fmt.Fprintf(file, "// Json helper functions for JsonFilter\n\n")
	fmt.Fprintf(file, "func Json(value json.RawMessage) *inputs.JsonFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.JsonFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")
}

func generateBytesHelpers(file *os.File) {
	fmt.Fprintf(file, "// Bytes helper functions for BytesFilter\n\n")
	fmt.Fprintf(file, "func Bytes(value []byte) *inputs.BytesFilter {\n")
	fmt.Fprintf(file, "\treturn &inputs.BytesFilter{Equals: &value}\n")
	fmt.Fprintf(file, "}\n\n")
}
