package generator

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/carlosnayan/prisma-go-client/internal/parser"
)

func GenerateInputs(schema *parser.Schema, outputDir string) error {
	inputsDir := filepath.Join(outputDir, "inputs")
	if err := os.MkdirAll(inputsDir, 0755); err != nil {
		return fmt.Errorf("failed to create inputs directory: %w", err)
	}

	if err := generateInputHelpersFile(inputsDir, schema); err != nil {
		return fmt.Errorf("failed to generate input helpers: %w", err)
	}

	for _, model := range schema.Models {
		inputFile := filepath.Join(inputsDir, toSnakeCase(model.Name)+"_input.go")
		if err := generateInputFile(inputFile, model, schema); err != nil {
			return fmt.Errorf("failed to generate inputs for %s: %w", model.Name, err)
		}
	}

	return nil
}

// generateInputFile generates input types for a model using templates
func generateInputFile(filePath string, model *parser.Model, schema *parser.Schema) error {
	pascalModelName := toPascalCase(model.Name)

	// Check if we need imports for fields that actually use the types directly
	// Required fields use base types, CreateManyArgs uses pointers with BaseGoType
	needsTime := false
	needsJson := false

	// First pass: check required fields
	for _, field := range model.Fields {
		if field.Type == nil || isAutoGenerated(field) || isRelation(field, schema) {
			continue
		}
		// Required DateTime fields need time import
		if field.Type.Name == "DateTime" && !field.Type.IsOptional {
			needsTime = true
		}
		// Required Json fields need json import
		if field.Type.Name == "Json" && !field.Type.IsOptional {
			needsJson = true
		}
	}

	// Prepare CreateInput fields
	createFields := make([]InputFieldInfo, 0)
	for _, field := range model.Fields {
		if isAutoGenerated(field) || isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		var goType string
		isOptional := field.Type != nil && field.Type.IsOptional

		// Optional fields use nullable wrappers, required fields use base types
		if isOptional {
			goType = fieldTypeToNullableWrapper(field.Type)
		} else {
			goType = fieldTypeToGoBase(field.Type)
		}
		jsonTag := toSnakeCase(field.Name)

		// Calculate BaseGoType ONLY for nullable fields (to use pointers instead of wrappers)
		baseGoType := ""
		if isOptional {
			// Map Nullable wrappers to their actual Go types for CreateManyArgs
			// Json and Bytes are excluded - they use wrappers because models don't use pointers
			switch goType {
			case "NullableString":
				baseGoType = "string"
			case "NullableInt":
				baseGoType = "int"
			case "NullableInt64":
				baseGoType = "int64"
			case "NullableFloat":
				baseGoType = "float64"
			case "NullableBool":
				baseGoType = "bool"
			case "NullableDateTime":
				baseGoType = "time.Time"
			default:
				// For Json, Bytes, and array types, leave empty to use GoType (NullableWrapper)
				baseGoType = ""
			}
		}

		createFields = append(createFields, InputFieldInfo{
			FieldName:  fieldName,
			GoType:     goType,
			BaseGoType: baseGoType,
			JSONTag:    jsonTag,
		})
	}

	// Check if we need time import for CreateManyArgs with *time.Time
	for _, field := range createFields {
		if field.BaseGoType == "time.Time" {
			needsTime = true
			break
		}
	}

	// Build stdlib imports after all checks
	stdlib := make([]string, 0, 2)
	if needsTime {
		stdlib = append(stdlib, "time")
	}
	if needsJson {
		stdlib = append(stdlib, "encoding/json")
	}

	// Prepare UpdateInput fields
	updateFields := make([]InputFieldInfo, 0)
	for _, field := range model.Fields {
		if isAutoGenerated(field) || isPrimaryKey(field) || isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		// UpdateInput fields are always optional - use nullable wrappers
		goType := fieldTypeToNullableWrapper(field.Type)
		jsonTag := toSnakeCase(field.Name)

		updateFields = append(updateFields, InputFieldInfo{
			FieldName: fieldName,
			GoType:    goType,
			JSONTag:   jsonTag,
		})
	}

	// Prepare WhereInput fields
	whereInputFields := make([]WhereInputFieldInfo, 0)
	for _, field := range model.Fields {
		if isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		filterType := getFilterType(field.Type)
		jsonTag := toSnakeCase(field.Name)

		whereInputFields = append(whereInputFields, WhereInputFieldInfo{
			FieldName:  fieldName,
			FilterType: filterType,
			JSONTag:    jsonTag,
		})
	}

	// Prepare Select fields
	selectFields := make([]InputSelectFieldInfo, 0)
	for _, field := range model.Fields {
		if isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		jsonTag := toSnakeCase(field.Name)

		selectFields = append(selectFields, InputSelectFieldInfo{
			FieldName: fieldName,
			JSONTag:   jsonTag,
		})
	}

	userModule, err := detectUserModule(filepath.Dir(filePath))
	if err != nil {
		userModule = "github.com/carlosnayan/prisma-go-client"
	}
	_, _, inputsPath, err := calculateImportPath(userModule, filepath.Dir(filepath.Dir(filePath)))
	if err != nil {
		inputsPath = ""
	}

	filtersPath := ""
	if inputsPath != "" {
		baseImportPath := inputsPath[:len(inputsPath)-len("/inputs")]
		filtersPath = baseImportPath + "/filters"
	}

	data := InputTemplateData{
		ModelName:        model.Name,
		PascalName:       pascalModelName,
		StdlibImports:    stdlib,
		FiltersPath:      filtersPath,
		CreateFields:     createFields,
		UpdateFields:     updateFields,
		WhereInputFields: whereInputFields,
		SelectFields:     selectFields,
	}

	templateNames := []string{
		"model_imports.tmpl",
		"createmany_args.tmpl",
		"select_input.tmpl",
	}

	return executeInputTemplates(filePath, templateNames, data)
}

// fieldTypeToGoBase returns the base Go type without pointers (for input types)
func fieldTypeToGoBase(fieldType *parser.FieldType) string {
	if fieldType == nil {
		return "interface{}"
	}

	if fieldType.IsUnsupported {
		return "string"
	}

	typeMapping := parser.GetTypeGoMapping()

	var goType string
	if mapped, ok := typeMapping[fieldType.Name]; ok {
		// Primitive type - return without pointer
		goType = mapped
	} else {
		// May be enum or model - for now string
		goType = "string"
	}

	// Se é array
	if fieldType.IsArray {
		return "[]" + goType
	}

	return goType
}

// isAutoGenerated checks if a field is auto-generated (id with autoincrement)
func isAutoGenerated(field *parser.ModelField) bool {
	hasID := false
	hasAutoIncrement := false
	for _, attr := range field.Attributes {
		if attr.Name == "id" {
			hasID = true
		}
		if attr.Name == "default" {
			for _, arg := range attr.Arguments {
				if arg.Value == "autoincrement()" {
					hasAutoIncrement = true
				}
			}
		}
	}

	if hasID && hasAutoIncrement {
		return true
	}

	return false
}

// isPrimaryKey checks if a field is a primary key
func isPrimaryKey(field *parser.ModelField) bool {
	for _, attr := range field.Attributes {
		if attr.Name == "id" {
			return true
		}
	}
	return false
}

// isRelation checks if a field is a relationship (non-primitive type)
// It returns false for enums, which are scalar types, not relationships
func isRelation(field *parser.ModelField, schema *parser.Schema) bool {
	if field.Type == nil {
		return false
	}

	// Known builtin types
	builtinTypes := map[string]bool{
		"String":   true,
		"Int":      true,
		"BigInt":   true,
		"Float":    true,
		"Decimal":  true,
		"Boolean":  true,
		"DateTime": true,
		"Json":     true,
		"Bytes":    true,
	}

	// If it's a builtin type, it's not a relation
	if builtinTypes[field.Type.Name] {
		return false
	}

	// Check if it's an enum - enums are scalar types, not relationships
	for _, enum := range schema.Enums {
		if enum.Name == field.Type.Name {
			return false
		}
	}

	// If it's not a builtin type and not an enum, it's probably a relationship
	return true
}

// getFilterType returns the appropriate Filter type for a field type
func getFilterType(fieldType *parser.FieldType) string {
	if fieldType == nil {
		return "StringFilter" // Default
	}

	typeMapping := parser.GetTypeGoMapping()
	if mapped, ok := typeMapping[fieldType.Name]; ok {
		switch mapped {
		case "string":
			return "StringFilter"
		case "int":
			return "IntFilter"
		case "int64":
			return "Int64Filter"
		case "float64":
			return "FloatFilter"
		case "bool":
			return "BooleanFilter"
		case "time.Time":
			return "DateTimeFilter"
		case "json.RawMessage":
			return "JsonFilter"
		case "[]byte":
			return "BytesFilter"
		}
	}

	// For enums and relationships, use StringFilter by default
	return "StringFilter"
}

func generateInputHelpersFile(inputsDir string, schema *parser.Schema) error {
	helpersFile := filepath.Join(inputsDir, "helpers.go")

	needsDateTime := false
	needsJson := false

	for _, model := range schema.Models {
		for _, field := range model.Fields {
			if field.Type == nil || isAutoGenerated(field) || isRelation(field, schema) {
				continue
			}

			typeMapping := parser.GetTypeGoMapping()
			if mapped, ok := typeMapping[field.Type.Name]; ok {
				switch mapped {
				case "time.Time":
					needsDateTime = true
				case "json.RawMessage":
					needsJson = true
				}
			}
		}
	}

	stdlibImports := make([]string, 0, 1)
	if needsDateTime {
		stdlibImports = append(stdlibImports, "time")
	}
	// encoding/json is always added by the template, so don't add here

	data := InputHelpersTemplateData{
		StdlibImports: stdlibImports,
		NeedsDateTime: needsDateTime,
		NeedsJson:     needsJson,
	}

	templateNames := []string{
		"helpers_imports.tmpl",
		"nullable_wrappers.tmpl",
	}

	return executeInputHelpersTemplates(helpersFile, templateNames, data)
}
