package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/carlosnayan/prisma-go-client/internal/parser"
)

// GenerateModels gera structs Go para cada model do schema
func GenerateModels(schema *parser.Schema, outputDir string) error {
	modelsDir := filepath.Join(outputDir, "models")
	if err := os.MkdirAll(modelsDir, 0755); err != nil {
		return fmt.Errorf("erro ao criar diretório models: %w", err)
	}

	for _, model := range schema.Models {
		modelFile := filepath.Join(modelsDir, toSnakeCase(model.Name)+".go")
		if err := generateModelFile(modelFile, model, schema); err != nil {
			return fmt.Errorf("erro ao gerar model %s: %w", model.Name, err)
		}
	}

	return nil
}

// generateModelFile gera o arquivo Go para um model
func generateModelFile(filePath string, model *parser.Model, schema *parser.Schema) error {
	file, err := os.Create(filePath)
	if err != nil {
		return err
	}
	defer file.Close()

	// Header
	fmt.Fprintf(file, "// Code generated by prisma generate. DO NOT EDIT.\n")
	fmt.Fprintf(file, "package models\n\n")

	// Determinar imports necessários
	imports := determineImports(model, schema)
	if len(imports) > 0 {
		fmt.Fprintf(file, "import (\n")
		for _, imp := range imports {
			fmt.Fprintf(file, "\t%q\n", imp)
		}
		fmt.Fprintf(file, ")\n\n")
	}

	// Struct
	pascalModelName := toPascalCase(model.Name)
	fmt.Fprintf(file, "// %s represents the model %s\n", pascalModelName, model.Name)
	fmt.Fprintf(file, "type %s struct {\n", pascalModelName)

	for _, field := range model.Fields {
		generateField(file, field, model.Name)
	}

	fmt.Fprintf(file, "}\n")

	return nil
}

// generateField gera um campo do struct
func generateField(file *os.File, field *parser.ModelField, modelName string) {
	fieldName := toPascalCase(field.Name)
	goType := fieldTypeToGo(field.Type, field.Attributes)
	jsonTag := toSnakeCase(field.Name)
	dbTag := field.Name

	// Verificar se tem @map
	for _, attr := range field.Attributes {
		if attr.Name == "map" && len(attr.Arguments) > 0 {
			if val, ok := attr.Arguments[0].Value.(string); ok {
				dbTag = val
			}
		}
	}

	tags := fmt.Sprintf("`json:\"%s\" db:\"%s\"`", jsonTag, dbTag)
	fmt.Fprintf(file, "\t%s %s %s\n", fieldName, goType, tags)
}

// fieldTypeToGo converte um FieldType do Prisma para tipo Go
func fieldTypeToGo(fieldType *parser.FieldType, attributes []*parser.Attribute) string {
	if fieldType == nil {
		return "interface{}"
	}

	if fieldType.IsUnsupported {
		return "string" // Unsupported vira string por padrão
	}

	// Verificar se é um enum ou model (relacionamento)
	// Por enquanto, assumimos que tipos não-primitivos são strings ou relacionamentos
	typeMapping := parser.GetTypeGoMapping()
	nullableMapping := parser.GetTypeGoMappingNullable()

	var goType string
	if mapped, ok := typeMapping[fieldType.Name]; ok {
		// Tipo primitivo
		if fieldType.IsOptional {
			if nullable, ok := nullableMapping[fieldType.Name]; ok {
				goType = nullable
			} else {
				goType = "*" + mapped
			}
		} else {
			goType = mapped
		}
	} else {
		// Pode ser enum ou model - por enquanto string
		if fieldType.IsOptional {
			goType = "*string"
		} else {
			goType = "string"
		}
	}

	// Se é array
	if fieldType.IsArray {
		return "[]" + strings.TrimPrefix(goType, "*")
	}

	return goType
}

// determineImports determina quais imports são necessários
func determineImports(model *parser.Model, schema *parser.Schema) []string {
	imports := make(map[string]bool)

	for _, field := range model.Fields {
		if field.Type == nil {
			continue
		}

		typeMapping := parser.GetTypeGoMapping()
		if mapped, ok := typeMapping[field.Type.Name]; ok {
			switch mapped {
			case "time.Time":
				imports["time"] = true
			case "json.RawMessage":
				imports["encoding/json"] = true
			}
		}
	}

	// Converter map para slice ordenada
	result := []string{}
	if imports["time"] {
		result = append(result, "time")
	}
	if imports["encoding/json"] {
		result = append(result, "encoding/json")
	}

	return result
}

// toPascalCase converte snake_case para PascalCase
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			result.WriteString(strings.ToUpper(part[:1]) + strings.ToLower(part[1:]))
		}
	}
	return result.String()
}

// toSnakeCase converte PascalCase para snake_case
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

// isStdlibImport checks if an import is from the standard library
func isStdlibImport(imp string) bool {
	stdlibPackages := map[string]bool{
		"context":       true,
		"reflect":       true,
		"time":          true,
		"encoding/json": true,
		"fmt":           true,
		"os":            true,
		"strings":       true,
		"sort":          true,
		"path/filepath": true,
	}

	return stdlibPackages[imp]
}
