package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/carlosnayan/prisma-go-client/internal/parser"
)

// GenerateQueries generates type-safe query builders for each model
func GenerateQueries(schema *parser.Schema, outputDir string) error {
	queriesDir := filepath.Join(outputDir, "queries")
	if err := os.MkdirAll(queriesDir, 0755); err != nil {
		return fmt.Errorf("failed to create queries directory: %w", err)
	}

	// Detect user module
	userModule, err := detectUserModule(outputDir)
	if err != nil {
		return fmt.Errorf("failed to detect user module: %w", err)
	}

	// Generate query_result.go
	queryResultFile := filepath.Join(queriesDir, "query_result.go")
	if err := generateQueryResultFile(queryResultFile, userModule, outputDir); err != nil {
		return fmt.Errorf("failed to generate query_result.go: %w", err)
	}

	// Generate query files for each model
	for _, model := range schema.Models {
		queryFile := filepath.Join(queriesDir, toSnakeCase(model.Name)+"_query.go")
		if err := generateQueryFile(queryFile, model, schema, userModule, outputDir); err != nil {
			return fmt.Errorf("failed to generate query for %s: %w", model.Name, err)
		}
	}

	return nil
}

// generateQueryResultFile generates the file with QueryResult type using templates
func generateQueryResultFile(filePath string, userModule, outputDir string) error {
	// Calculate local import path for builder
	builderPath, _, err := calculateLocalImportPath(userModule, outputDir)
	if err != nil {
		builderPath = "github.com/carlosnayan/prisma-go-client/generated/builder"
	}

	// Prepare template data
	data := QueryResultTemplateData{
		BuilderPath: builderPath,
	}

	// Generate using template
	return executeModelTemplate(filePath, "queries", "queries", "query_result.tmpl", data)
}

// generateQueryFile generates the query builder file for a model using templates
func generateQueryFile(filePath string, model *parser.Model, schema *parser.Schema, userModule, outputDir string) error {
	// Determine required imports
	imports := determineQueryImports(userModule, outputDir, model)

	// Separate stdlib and third-party imports
	stdlib := make([]string, 0, len(imports))
	thirdParty := make([]string, 0, len(imports))

	for _, imp := range imports {
		if isStdlibImport(imp) {
			stdlib = append(stdlib, imp)
		} else {
			thirdParty = append(thirdParty, imp)
		}
	}

	// Calculate import paths
	modelsPath, _, inputsPath, err := calculateImportPath(userModule, outputDir)
	if err != nil {
		modelsPath = "github.com/carlosnayan/prisma-go-client/generated/models"
		inputsPath = "github.com/carlosnayan/prisma-go-client/generated/inputs"
	}

	builderPath, _, err := calculateLocalImportPath(userModule, outputDir)
	if err != nil {
		builderPath = "github.com/carlosnayan/prisma-go-client/generated/builder"
	}

	// Prepare fields for filter conversion
	fields := make([]FieldFilterInfo, 0)
	for _, field := range model.Fields {
		if isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		// Get the actual database column name (check for @map attribute)
		dbFieldName := field.Name
		for _, attr := range field.Attributes {
			if attr.Name == "map" && len(attr.Arguments) > 0 {
				if val, ok := attr.Arguments[0].Value.(string); ok {
					dbFieldName = val
					break
				}
			}
		}
		filterType := getFilterType(field.Type)

		fields = append(fields, FieldFilterInfo{
			FieldName:   fieldName,
			DBFieldName: dbFieldName,
			FilterType:  filterType,
		})
	}

	// Prepare select fields
	selectFields := make([]SelectFieldInfo, 0)
	for _, field := range model.Fields {
		if isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		// Get the actual database column name (check for @map attribute)
		columnName := field.Name
		for _, attr := range field.Attributes {
			if attr.Name == "map" && len(attr.Arguments) > 0 {
				if val, ok := attr.Arguments[0].Value.(string); ok {
					columnName = val
					break
				}
			}
		}
		selectFields = append(selectFields, SelectFieldInfo{
			FieldName:  fieldName,
			ColumnName: columnName,
		})
	}

	// Prepare update fields
	updateFields := make([]UpdateFieldInfo, 0)
	for _, field := range model.Fields {
		if isAutoGenerated(field) || isPrimaryKey(field) || isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		// Get the actual database column name (check for @map attribute)
		dbFieldName := field.Name
		for _, attr := range field.Attributes {
			if attr.Name == "map" && len(attr.Arguments) > 0 {
				if val, ok := attr.Arguments[0].Value.(string); ok {
					dbFieldName = val
					break
				}
			}
		}

		updateFields = append(updateFields, UpdateFieldInfo{
			FieldName:            fieldName,
			DBName:               dbFieldName,
			GoType:               mapPrismaTypeToGo(field.Type),
			IsNullable:           field.Type != nil && field.Type.IsOptional,
			IsNonPointerOptional: isNonPointerOptionalType(field.Type),
		})
	}

	// Prepare create fields
	createFields := make([]CreateFieldInfo, 0)
	for _, field := range model.Fields {
		if isAutoGenerated(field) || isRelation(field, schema) {
			continue
		}
		fieldName := toPascalCase(field.Name)
		// Get the actual database column name (check for @map attribute)
		dbName := field.Name
		for _, attr := range field.Attributes {
			if attr.Name == "map" && len(attr.Arguments) > 0 {
				if val, ok := attr.Arguments[0].Value.(string); ok {
					dbName = val
					break
				}
			}
		}
		isOptional := field.Type != nil && field.Type.IsOptional
		isNonPointerOptional := isNonPointerOptionalType(field.Type)
		goType := mapPrismaTypeToGo(field.Type)

		// Calculate BaseGoType for nullable fields (for CreateMany pointers)
		baseGoType := ""
		if isOptional {
			// Map base types to themselves for pointer generation in CreateManyArgs
			// mapPrismaTypeToGo returns base types (string, not *string) for CreateFields
			switch goType {
			case "string":
				baseGoType = "string"
			case "int":
				baseGoType = "int"
			case "int64":
				baseGoType = "int64"
			case "float64":
				baseGoType = "float64"
			case "bool":
				baseGoType = "bool"
			case "time.Time":
				baseGoType = "time.Time"
			// Json and Bytes don't get BaseGoType - they stay as non-pointer types
			case "json.RawMessage", "[]byte":
				baseGoType = "" // Keep empty to use NullableWrapper
			}
		}

		createFields = append(createFields, CreateFieldInfo{
			FieldName:            fieldName,
			DBName:               dbName,
			GoType:               goType,
			BaseGoType:           baseGoType,
			IsNullable:           isOptional,
			IsRequired:           !isOptional && !hasDefaultValue(field) && !isAutoGenerated(field),
			IsNonPointerOptional: isNonPointerOptional,
		})
	}

	// Get model metadata
	columns := getModelColumns(model, schema)
	primaryKey := getPrimaryKey(model)
	tableName := getTableName(model)

	// Calculate table package import
	tablePackageName := toSnakeCase(model.Name)
	// Get the base module path from modelsPath (remove "/models" suffix)
	baseModulePath := strings.TrimSuffix(modelsPath, "/models")
	tablePackageImport := baseModulePath + "/tables/" + tablePackageName

	// Prepare template data
	data := QueryTemplateData{
		ModelName:          model.Name,
		PascalName:         toPascalCase(model.Name),
		LowerName:          strings.ToLower(model.Name),
		StdlibImports:      stdlib,
		ThirdPartyImports:  thirdParty,
		BuilderPath:        builderPath,
		ModelsPath:         modelsPath,
		InputsPath:         inputsPath,
		TablePackageImport: tablePackageImport,
		TablePackageName:   tablePackageName,
		Fields:             fields,
		SelectFields:       selectFields,
		UpdateFields:       updateFields,
		CreateFields:       createFields,
		Columns:            columns,
		PrimaryKey:         primaryKey,
		TableName:          tableName,
	}

	// Define all templates in correct order
	allTemplateNames := []string{
		// Base templates
		"imports.tmpl",
		"query_struct.tmpl",
		"basic_methods.tmpl",
		"createmany_builder.tmpl",
		// Ent-style API builders
		"findfirst_builder.tmpl",
		"findmany_builder.tmpl",
		"count_builder.tmpl",
		"delete_builder.tmpl",
		"create_builder.tmpl",
		"updatemany_builder.tmpl",
		"update_builder.tmpl",
		"updateone_builder.tmpl",
		"apply_condition_helper.tmpl",
	}

	// Generate all templates in single call to avoid file overwrite
	return executeQueryTemplates(filePath, allTemplateNames, data)
}

// isNonPointerOptionalType checks if a field type doesn't use pointers in models
// even when optional (json.RawMessage and []byte)
func isNonPointerOptionalType(fieldType *parser.FieldType) bool {
	if fieldType == nil {
		return false
	}
	// Json and Bytes types don't use pointers in models even when optional
	return fieldType.Name == "Json" || fieldType.Name == "Bytes"
}

// hasDefaultValue checks if a field has a @default attribute
func hasDefaultValue(field *parser.ModelField) bool {
	for _, attr := range field.Attributes {
		if attr.Name == "default" {
			return true
		}
	}
	return false
}

// determineQueryImports determines which imports are needed for query files
func determineQueryImports(userModule, outputDir string, model *parser.Model) []string {
	// Calculate import paths for generated packages
	modelsPath, _, inputsPath, err := calculateImportPath(userModule, outputDir)
	if err != nil {
		// Fallback to old paths if detection fails
		modelsPath = "github.com/carlosnayan/prisma-go-client/generated/models"
		inputsPath = "github.com/carlosnayan/prisma-go-client/generated/inputs"
	}

	// Calculate local import path for builder (standalone package)
	builderPath, _, err := calculateLocalImportPath(userModule, outputDir)
	if err != nil {
		// Fallback to old path if detection fails
		builderPath = "github.com/carlosnayan/prisma-go-client/generated/builder"
	}

	imports := []string{
		"context",
		"fmt",
		"reflect",
		"strings",
	}

	// Check if any field is DateTime to determine if time import is needed
	needsTime := false
	needsJSON := false
	for _, field := range model.Fields {
		if field.Type != nil {
			typeName := strings.ToLower(field.Type.Name)
			if typeName == "datetime" {
				needsTime = true
			}
			if typeName == "json" {
				needsJSON = true
			}
		}
	}

	if needsJSON {
		imports = append(imports, "encoding/json")
	}

	if needsTime {
		imports = append(imports, "time")
	}

	// Add package imports
	imports = append(imports, builderPath, modelsPath, inputsPath)

	// Add table package import for Condition types
	// Build the full module path for the table package
	tablePackageName := toSnakeCase(model.Name)
	// Get the base module path from modelsPath (remove "/models" suffix)
	baseModulePath := strings.TrimSuffix(modelsPath, "/models")
	tablePackageImport := baseModulePath + "/tables/" + tablePackageName
	imports = append(imports, tablePackageImport)

	return imports
}
